# Generated by Django 4.0.6 on 2022-07-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='url_curta',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
