# Generated by Django 4.0.6 on 2022-07-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_alter_links_url_curta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='url_curta',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
