# Generated by Django 4.0.6 on 2022-07-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_alter_links_url_curta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='url_original',
            field=models.URLField(max_length=2048, unique=True),
        ),
    ]
